name: conpy
channels:
- conda-forge
dependencies:
- python>=3.11
- h5io
- h5py
- ipython
- jupyter
- matplotlib
- mne
- numpy
- numpydoc
- pip
- pyside6
- pytest
- pytest-cov
- scipy
- sphinx
- sphinx_bootstrap_theme
- sphinx_gallery
- tqdm
- traits
- traitsui
- vtk
